spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=storedb;encrypt=true;trustServerCertificate=true;
    username: sa
    password: dockerStrongPwd123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
